// <auto-generated />
using System;
using GradingSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradingSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    partial class GradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradingSystem.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseSqlPath")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("GivenApiBaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GivenZipPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("\"ExamSessionId\" IS NULL");

                    b.HasIndex("ExamSessionId", "Code")
                        .IsUnique()
                        .HasFilter("\"ExamSessionId\" IS NOT NULL");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("GradingRound")
                        .HasColumnType("text");

                    b.Property<Guid?>("LabAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("LabAssignmentId");

                    b.ToTable("ExportJobs");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.GradingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradingRound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("GradingJobs");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<Guid?>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.ToTable("LabAssignments");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabGradingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LabSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabSubmissionId");

                    b.ToTable("LabGradingJobs");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LabAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabAssignmentId", "StudentCode")
                        .IsUnique();

                    b.ToTable("LabSubmissions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabTestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiGenerated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExpectJson")
                        .HasColumnType("text");

                    b.Property<int>("ExpectedStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<Guid>("LabAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SaveTokenFrom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LabAssignmentId");

                    b.ToTable("LabTestCases");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabTestCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResponse")
                        .HasColumnType("text");

                    b.Property<int?>("ActualStatusCode")
                        .HasColumnType("integer");

                    b.Property<decimal>("AwardedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("LabGradingJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabTestCaseId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ManualOverrideScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabGradingJobId");

                    b.HasIndex("LabTestCaseId");

                    b.ToTable("LabTestCaseResults");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ExamSessionId", "Username")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactFolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.QuestionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AdjustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdjustedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("AdjustedScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<Guid?>("GradingJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("GradingJobId", "QuestionId")
                        .IsUnique()
                        .HasFilter("\"GradingJobId\" IS NOT NULL");

                    b.ToTable("QuestionResults");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ReviewNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("ReviewNotes");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactZipPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradingRound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasArtifact")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ParticipantId", "GradingRound")
                        .IsUnique()
                        .HasFilter("\"ParticipantId\" IS NOT NULL");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("InputJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("Assignments")
                        .HasForeignKey("ExamSessionId");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ExportJob", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId");

                    b.HasOne("GradingSystem.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany()
                        .HasForeignKey("ExamSessionId");

                    b.HasOne("GradingSystem.Domain.Entities.LabAssignment", "LabAssignment")
                        .WithMany()
                        .HasForeignKey("LabAssignmentId");

                    b.Navigation("Assignment");

                    b.Navigation("ExamSession");

                    b.Navigation("LabAssignment");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.GradingJob", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Submission", "Submission")
                        .WithMany("GradingJobs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabAssignment", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Semester", "Semester")
                        .WithMany("LabAssignments")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabGradingJob", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.LabSubmission", "LabSubmission")
                        .WithMany("GradingJobs")
                        .HasForeignKey("LabSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabSubmission");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabSubmission", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.LabAssignment", "LabAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("LabAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabAssignment");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabTestCase", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.LabAssignment", "LabAssignment")
                        .WithMany("TestCases")
                        .HasForeignKey("LabAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabAssignment");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabTestCaseResult", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.LabGradingJob", "LabGradingJob")
                        .WithMany("Results")
                        .HasForeignKey("LabGradingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingSystem.Domain.Entities.LabTestCase", "LabTestCase")
                        .WithMany()
                        .HasForeignKey("LabTestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabGradingJob");

                    b.Navigation("LabTestCase");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Participant", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Participants")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingSystem.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("Participants")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Question", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Questions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.QuestionResult", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.GradingJob", "GradingJob")
                        .WithMany()
                        .HasForeignKey("GradingJobId");

                    b.HasOne("GradingSystem.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingSystem.Domain.Entities.Submission", "Submission")
                        .WithMany("QuestionResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingJob");

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ReviewNote", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Submission", "Submission")
                        .WithOne("ReviewNote")
                        .HasForeignKey("GradingSystem.Domain.Entities.ReviewNote", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Submission", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GradingSystem.Domain.Entities.Participant", "Participant")
                        .WithMany("Submissions")
                        .HasForeignKey("ParticipantId");

                    b.Navigation("Assignment");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("GradingSystem.Domain.Entities.Question", "Question")
                        .WithMany("TestCases")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabAssignment", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabGradingJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.LabSubmission", b =>
                {
                    b.Navigation("GradingJobs");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Question", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Semester", b =>
                {
                    b.Navigation("LabAssignments");
                });

            modelBuilder.Entity("GradingSystem.Domain.Entities.Submission", b =>
                {
                    b.Navigation("GradingJobs");

                    b.Navigation("QuestionResults");

                    b.Navigation("ReviewNote");
                });
#pragma warning restore 612, 618
        }
    }
}
